version: '3.8'

services:
  frontend:
    build:
      context: ./bus-booking-frontend
    ports:
      - "80:80"

  backend:
    build:
      context: ./bus-booking-backend
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://mongo:27017/busbooking
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
